export const CREATE_CONTACT_COMPANY = "CREATE_CONTACT_COMPANY";
export const ALL_CONTACT_COMPANIES = "ALL_CONTACT_COMPANIES";
export const UPDATE_CONTACT_COMPANY = "UPDATE_CONTACT_COMPANY";
export const DELETE_CONTACT_COMPANY = "DELETE_CONTACT_COMPANY";
export const UPDATED = "UPDATED";
export const CREATED = "CREATED";
export const PAGING_DATA = "PAGING_DATA";
export const TOTAL_DATA = "TOTAL_DATA";
export const TOTAL_CONTACT_COMPANY = "TOTAL_CONTACT_COMPANY";
export const CONTACT_COMPANY_PROFILE = "CONTACT_COMPANY_PROFILE";

